### ISSUE TITLE
Kategorie Root Elemente sollten auch wählbar sein

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#12]
Die Parent Elemente der Kategorien sind auch direkt wählbar und werden dann auch ausgegeben.
Also zB "Kids & Family" oder "Sports".

Hier die Aktuelle Liste:
https://podcasts.apple.com/us/genre/podcasts/id26

Hier ein Beispiel in dem nur die Root Kategorie "Kids & Family" verwendet wird:
https://podcasts.apple.com/de/podcast/kidspods-das-podcastportal-f%C3%BCr-kinder/id74190097

**Comment by Metis77** [comment]
from https://help.apple.com/itc/podcasts_connect/#/itcb54353390

zum Beispiel: Single category:

`  <itunes:category text="History" />`

**Comment by stefansl** [comment]
Added in 4f905c5c8c3207013f9d4053931ee2fd05bd3b0d
