### ISSUE TITLE
Item image (enhancement)

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#13]
Autoadd item images from News,
with transform / crop to aspect ration 1:1 and max 3000x3000px.

for example:

```
<itunes:image href="http://www.example.com/image3000x3000.png"/>
```

**Comment by stefansl** [comment]
Is there any documentation about item images?

**Comment by Metis77** [comment]
from https://itunespartner.apple.com/podcasts/articles/design-your-artwork-3059
> While show cover art is a requirement for all podcast submissions, episode images are optional. 

syntax is the same as for the channel image, as far as I know.

**Comment by stefansl** [comment]
Added in 6d7ce0527b67708888f1ca8dc0a393b54d8af2bb and 4d8edd95cb8a95c74e943634b30782feba743016
