### ISSUE TITLE
Add podcasts in page layouts 

### ISSUE THREAD

**Issue by stefansl** [clickpress/contao-news-podcasts#14]
Add selectable podcast xml to page layouts in section RSS/Atom-Feeds

**Comment by stefansl** [comment]
see: https://support.google.com/podcast-publishers/answer/9890054?hl=de

**Comment by stefansl** [comment]
Added in a32476929890cec75c930b2a0e0ef3db6c1d3ea0  and cf69b14771966b7c5c5cc2dafe2d304cf1d0f4b8

**Comment by Metis77** [comment]
does this respect the case, when u add multiple feeds on one page?

**Comment by stefansl** [comment]
YES :)
