### ISSUE TITLE
Respect line breaks and links (enhancement)

### ISSUE THREAD

**Issue by manjarco** [clickpress/contao-news-podcasts#16]
At the moment all links and line breaks are stripped from the news teaser when being written into the xml. 
As per https://help.apple.com/itc/podcasts_connect/#/itcb54353390 (under "description") regular links are allowed in the CDATA.
Some podcast apps also render plain-text line breaks in the description tag.

Would be great to see both things in this extension some time.

**Comment by stefansl** [comment]
As a quickfix change https://github.com/clickpress/contao-news-podcasts/blob/3a59735e4e05626914028627d2343fdcdcf24374/src/NewsPodcasts.php#L290

to
```php
$objItem->teaser = $objPodcasts->teaser ?? $objPodcasts->description; 
```

**Comment by manjarco** [comment]
Ok, I'm very sorry. It seems that links have been there all the time (our editor just didn't use them right in the last couple episodes). Now just the line breaks remain.

I'm a bit hesitant to kill the self:cleanHtml part. Won't that mean that everything else like <span>, <strong>, … will be written into the teaser aswell?

**Comment by stefansl** [comment]
The questions is: what is allowed in the meta and in the episode description? At Google Podcasts and at iTunes.
