### ISSUE TITLE
Update XML and "Show from/until"

### ISSUE THREAD

**Issue by manjarco** [clickpress/contao-news-podcasts#17]
Is there a way to update the XML not only after saving a news item but also when the "show from" oder "show until" dates are reached? Otherwise if a new news item with a podcast is set to be published in the future with the "show from" functionality the editor has to manually regenerate the XML at the correct time, rendering "show from" unnecessary.

I know this might be a tricky one, but maybe a workaround might be to be able trigger the XML update via a cronjob? Otherwise disable the "show from/until" fields when a podcast is added to the news item so no one runs into that trap?

**Comment by stefansl** [comment]
The contao periodic command scheduler is triggering generateXmlFiles by default, which triggers this hook in news_podcasts:
https://github.com/clickpress/contao-news-podcasts/blob/3a59735e4e05626914028627d2343fdcdcf24374/src/EventListener/GenerateXmlFilesListener.php#L18

So, your solution should be executing a real cronjob according to https://docs.contao.org/dev/framework/cron/

**Comment by manjarco** [comment]
Thanks!

I'm guessing the hook doesn't write an entry in the backend system-log!? Because I can't find any when looking at the times the command scheduler did it's other tasks.
