### ISSUE TITLE
Correct pubDate format

### ISSUE THREAD

**Issue by manjarco** [clickpress/contao-news-podcasts#18]
As https://help.apple.com/itc/podcasts_connect/#/itcb54353390 states:

> Format the date using the RFC 2822 specifications. For example: Wed, 15 Jun 2019 19:00:00 GMT.

news-podcasts still uses the old RFC822 format. This is only an issue in some podcast readers like Deezer or analytics tools. Apple podcasts, Google podcasts, Spotify still recognize the old format.

**Comment by stefansl** [comment]
Fixed in https://github.com/clickpress/contao-news-podcasts/issues/18. Thanks!
