### ISSUE TITLE
Incorrect PHP version requirement

### ISSUE THREAD

**Issue by lukasbableck** [clickpress/contao-news-podcasts#19]
According to the composer.json, PHP ^7.4 and ^8.0 can be used.
However, some PHP 8 exclusive features are used in this extension. 
For example the null safe operator here: https://github.com/clickpress/contao-news-podcasts/blob/master/src/NewsPodcastsBackend.php#L167
Because of this the extension does not work with PHP 7.4, so IMO the version requirement should be changed since PHP 7.4 is EOL anyways.

**Comment by fritzmg** [comment]
Since a version with the wrong PHP requirements has already been released, the correct way to fix this is to remove all PHP 8 specific features, release that as a new version, and then re-add them again and release that as a new version (with updated dependencies).

**Comment by stefansl** [comment]
You're both right. But at the moment I don't have the time to fix this issue

**Comment by Metis77** [comment]
I would like to use this awesome bundle in january together with Contao 4.13 and PHP 8.1.
@stefansl Any chance you can have a look?
I can support you with testing and money (lets talk).

**Comment by stefansl** [comment]
@Metis77 No problem, let's have a call

**Comment by stefansl** [comment]
Fixed in 60ffb92009ab3d8b3242b9d58d499d419c937f96
