### ISSUE TITLE
RSS guid

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#2]
```php 
      // Add the GUID
          if ($objItem->guid) {
              // Add the isPermaLink attribute if the guid is not a link (see #4930)
              if (0 !== strncmp($objItem->guid, 'http://', 7) && 0 !== strncmp($objItem->guid, 'https://', 8)) {
                  $xml .= '<guid isPermaLink="false">' . $objItem->guid . '</guid>';
              } else {
                  $xml .= '<guid>' . $objItem->guid . '</guid>';
              }
          } else {
              $xml .= '<guid>' . \StringUtil::specialchars($objItem->link) . '</guid>';
          }
```

Wo kommt denn eigentlich die guid her?
Es sollte entweder  hier einfach die **ID** des News Eintrags stehen, oder der **Deeplink** zum newseintrag.
Bisher wird hier bei mir die "BAsisURL" aus den Feed Einstellungen verwendet.

Apple beschreibt die guid so:
> What's an episode GUID?
Each episode in your podcast has a globally unique identifier (GUID). It’s very important that each episode has a unique, alphanumeric GUID that never changes, even if an episode’s metadata, like title or enclosure URL, do change.

>If a GUID is not provided, an episode’s enclosure URL will be used instead. In this case, make sure that an episode’s enclosure URL is also unique and never changes.

**Comment by stefansl** [comment]
Fixed in faa8c6f6e55cab9d4f6239eab3511dbb4eae12b5
