### ISSUE TITLE
Newslist: keine Ausgabe der "nicht-Podcast"-Beiträge mehr

### ISSUE THREAD

**Issue by petrad** [clickpress/contao-news-podcasts#20]
Mit Update auf Contao 4.13.14 und PHP 8.0 werden "keine-Podcast"-Newslisten nicht mehr ausgegeben: "Keine Nachrichten vorhanden". Wird das News Podcasts-Modul deinstalliert, erscheinen die Beiträge wieder. 

Herzliche Grüße, Petra

**Comment by stefansl** [comment]
See https://github.com/clickpress/contao-news-podcasts/issues/19
