### ISSUE TITLE
Install problem in Contao 4.13.23

### ISSUE THREAD

**Issue by JLBA** [clickpress/contao-news-podcasts#22]
Hello,
I'm trying to install contao-news-podcast in Contao 4.13.23 /Php 7.4 with Contao Manager. At the end of the install, I execute database processes. The first ones are ok. Then it asks for 
`Change field tl_news_podcasts_feed.alias VARCHAR(128) CHARACTER SET utf8 DEFAULT '' NOT NULL COLLATE `utf8_bin`

I clic on execute, it seems to be ok but it asks it again... and again... and again...

Then I go to the backoffice, create a new podcast but when saving it, I got this error message : `Return value of Clickpress\NewsPodcasts\NewsPodcastsBackend::checkFeedAlias() must be an instance of Clickpress\NewsPodcasts\mixed, string returned`

What can i do ? Thanks.

**Comment by JLBA** [comment]
Little up.

**Comment by JLBA** [comment]
Same problem with a fresh Contao 4.9 on php 8.1.

Install Tool says : 
`ALTER TABLE tl_news_podcasts_feed CHANGE alias alias VARCHAR(128) CHARACTER SET utf8 DEFAULT '' NOT NULL COLLATE `utf8_bin`
`
And, in the BO / News / Podcast feeds : 
`preg_replace(): Argument #3 ($subject) must be of type array|string, null given`

**Comment by stefansl** [comment]
Thanks to @Metis77 the development will be continued for Contao 5.3. Your issue should be solved in Contao 4.13 with PHP 8

**Comment by JLBA** [comment]
Hi @stefansl  thanks for your answer.
I'm just starting a website where I'll have to host podcasts. Do you know when the issue will be fixed ?

**Comment by stefansl** [comment]
Should be fixed in one or two weeks :)

**Comment by stefansl** [comment]
The error itself should be fixed already in 30dbea5d4bfcd8d729452415f60e03937860711f ... but the branch contao-5 could still be buggy. If you want, you can test it via `composer require clickpress/contao-news-podcasts:dev-contao-5`

**Comment by JLBA** [comment]
Thanks for the info. I'm working on Contao 4.13. I can wait for one or two weeks.

**Comment by stefansl** [comment]
Fixed in https://github.com/clickpress/contao-news-podcasts/commit/c20fd09f2c64160b6d4f70f4ecc024a2b5795403
