### ISSUE TITLE
News lists empty in Contao 4.13.35 / PHP 8.1

### ISSUE THREAD

**Issue by johannes-bittner** [clickpress/contao-news-podcasts#23]
In Contao 4.13.35 / PHP 8.1, news list modules as well do not display any news items anymore (regardless of the news template chosen), the archive list module does, however. Upon uninstall, the items are displayed again.

**Comment by stefansl** [comment]
I tried to reproduce this, but everythings works fine.

**Comment by stefansl** [comment]
I had a similiar issue an I guess, yours is fixed in c7b2156f88ee0545ed3d2d7acfda1c9be74debc4, too
