### ISSUE TITLE
Feature: Additional secondary podcast categories

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#24]
According to:
https://podcasters.apple.com/de-de/support/1691-apple-podcasts-categories
and in easier words:
https://castos.com/itunes-podcast-category-list/

It is adviceable to set one Primary Category (optionally with a subcategory)
And up to 2 Secondary Categories (optianlyy withe subcategories each).

This could be a future feature.

**Comment by stefansl** [comment]
Added in 9d3d78c3e9490b4408fa3e6e5cae40b5af03a279, ee707c77452fa5cddc7abdf5fa0097840839743b and 6a9537655b120d6e3e09e3878d42bc5a59638840
