### ISSUE TITLE
BaseURL changes on save

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#4]
Wenn man die Feed Einstellungen speichert, wird an die BaseURL ein / angehängt.

So wird zb aus `https://elternzeitung.de/podcasts`-> `https://elternzeitung.de/podcasts/` was dann zu 404 führt.

**Comment by stefansl** [comment]
Fixed in 3de9aa0757d9a40eb9563ea01ca1accf4688861b
