### ISSUE TITLE
$this->podcastUrl contains url twice

### ISSUE THREAD

**Issue by Metis77** [clickpress/contao-news-podcasts#5]
`$this->podcastUrl` contains the url to the feed twice:

`<atom:link href="https://elternzeitung.de/share/podcast-hechts-hilfe.xml/share/podcast-hechts-hilfe.xml" rel="self" type="application/rss+xml"/>`

**Comment by stefansl** [comment]
I cannot reproduce this ...

**Comment by Metis77** [comment]
seams to work right now.
lets close the issue, until this comus up again
